lib/pastie_web/router.ex
defmodule PastieWeb.Router do
  use PastieWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PastieWeb do
    pipe_through :browser

    get "/status", StatusController, :show

    get "/pastes", PasteController, :index
    get "/pastes/:id", PasteController, :show

    delete "/paste/*path", PasteController, :delete
    patch "/paste/*path", PasteController, :patch
    post "/paste/*path", PasteController, :post
    put "/paste/*path", PasteController, :put
  end

  # Other scopes may use custom stacks.
  # scope "/api", PastieWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: PastieWeb.Telemetry
    end
  end
end

lib/pastie/application.ex
defmodule Pastie.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    children = [
      Pastie.Repo,
      # Start the Telemetry supervisor
      PastieWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: Pastie.PubSub},
      # Start the Endpoint (http/https)
      PastieWeb.Endpoint
      # Start a worker by calling: Pastie.Worker.start_link(arg)
      # {Pastie.Worker, arg}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Pastie.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    PastieWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/pastie/paste.ex
defmodule Pastie.Paste do
  defstruct [:id, :ts, :path, :method, :body]
end

lib/pastie/repo.ex
defmodule Pastie.Repo do
  use GenServer

  def start_link(opts \\ []) do
    GenServer.start_link(__MODULE__, :ok, Keyword.merge([name: __MODULE__], opts))
  end

  def init(:ok) do
    {:ok, []}
  end

  def index do
    GenServer.call(__MODULE__, :index)
  end

  def get(id) do
    GenServer.call(__MODULE__, {:get, id})
  end

  def store(paste) do
    GenServer.call(__MODULE__, {:store, paste})
  end

  def handle_call(:index, _from, state) do
    {:reply, state, state}
  end

  def handle_call({:get, id}, _from, state) do
    paste = Enum.find(state, & &1.id == id)
    {:reply, paste, state}
  end

  def handle_call({:store, request}, _from, state) do
    {:reply, :ok, [request | state]}
  end
end

lib/pastie_web/controllers/page_controller.ex
defmodule PastieWeb.PageController do
  use PastieWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/pastie_web/controllers/paste_controller.ex
defmodule PastieWeb.PasteController do
  use PastieWeb, :controller

  alias Pastie.{Paste,Repo}

  def index(conn, _params) do
    pastes = Repo.index()
    render(conn, "index.html", pastes: pastes)
  end

  def show(conn, %{"id" => id}) do
    paste = Repo.get(id)
    render(conn, "show.html", paste: paste)
  end

  def delete(conn, _params) do
    handle(conn)
  end

  def patch(conn, _params) do
    handle(conn)
  end

  def post(conn, _params) do
    handle(conn)
  end

  def put(conn, _params) do
    handle(conn)
  end

  defp handle(conn) do
    Repo.store(%Paste{
      id: List.first(get_req_header(conn, "x-request-id")) || List.first(get_resp_header(conn, "x-request-id")) || gen_id(),
      ts: DateTime.utc_now(),
      path: String.replace_leading(conn.request_path, "/paste", ""),
      body: conn.private.raw_body,
      method: conn.method,
    })

    send_resp(conn, :ok, "")
  end

  defp gen_id do
    binary = <<
      System.system_time(:nanosecond)::64,
      :erlang.phash2({node(), self()}, 16_777_216)::24,
      :erlang.unique_integer()::32
    >>

    Base.url_encode64(binary)
  end
end

lib/pastie_web/controllers/status_controller.ex
defmodule PastieWeb.StatusController do
  use PastieWeb, :controller

  def show(conn, _params) do
    text conn, "ok"
  end
end

lib/pastie_web/views/error_view.ex
defmodule PastieWeb.ErrorView do
  use PastieWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/pastie_web/views/layout_view.ex
defmodule PastieWeb.LayoutView do
  use PastieWeb, :view
end

lib/pastie_web/views/page_view.ex
defmodule PastieWeb.PageView do
  use PastieWeb, :view
end

lib/pastie_web/views/paste_view.ex
defmodule PastieWeb.PasteView do
  use PastieWeb, :view
end

lib/pastie_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Pastie · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <li><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %></li>
            <% end %>
          </ul>
        </nav>
        <a href="https://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
  </body>
</html>

lib/pastie_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h1>
  <p>Peace-of-mind from prototype to production</p>
</section>

<section class="row">
  <article class="column">
    <h2>Resources</h2>
    <ul>
      <li>
        <a href="https://hexdocs.pm/phoenix/overview.html">Guides &amp; Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix/blob/v1.5/CHANGELOG.md">v1.5 Changelog</a>
      </li>
    </ul>
  </article>
  <article class="column">
    <h2>Help</h2>
    <ul>
      <li>
        <a href="https://elixirforum.com/c/phoenix-forum">Forum</a>
      </li>
      <li>
        <a href="https://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on Freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">Twitter @elixirphoenix</a>
      </li>
      <li>
        <a href="https://elixir-slackin.herokuapp.com/">Elixir on Slack</a>
      </li>
    </ul>
  </article>
</section>

lib/pastie_web/templates/paste/index.html.eex
<h2>Pastes</h2>

<ul>
<%= for paste <- @pastes do %>
  <li><%= link "#{paste.method} #{paste.path}", to: Routes.paste_path(@conn, :show, paste.id) %></li>
<% end %>
</ul>

lib/pastie_web/templates/paste/show.html.eex
<h1>Paste</h1>

<p>
  <label>path</label>
  <%= @paste.path %>
</p>

<p>
  <label>timestamp</label>
  <%= @paste.ts %>
</p>

<p>
  <label>method</label>
  <%= @paste.method %>
</p>

<p>
  <label>body</label>
  <pre>
  <%= @paste.body %>
  </pre>
</p>